{% set version = "0.9.9.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fts
  version: {{ version|replace("-", "_") }}

source:
  fn: fts_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/fts_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/fts/fts_{{ version }}.tar.gz
  sha256: 981fb8f8f3bbc63edd4bed7be34bbf541182b0cae3c3fd088dbb7627f4ce4374

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-bh
    - r-zoo
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-bh
    - r-zoo
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('fts')"  # [not win]
    - "\"%R%\" -e \"library('fts')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=fts
  license: GPL-3
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
  summary: fast operations for time series objects

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - nsoranzo
