{% set version = "0.9.9.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fts
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fts_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fts/fts_{{ version }}.tar.gz
  sha256: f894988ab793508c56976cd845646baa62a43aa2b94c6d491b27ac964284fc22

build:
  merge_build_host: True  # [win]
  number: 1004
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh
    - r-zoo
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bh
    - r-zoo

test:
  commands:
    - $R -e "library('fts')"           # [not win]
    - "\"%R%\" -e \"library('fts')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=fts
  license: GPL-3.0-only
  license_family: GPL3
  summary: fast operations for time series objects
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo
