travis:
  secure:
    BINSTAR_TOKEN: VzQxXW6VMtkl8ceRtAyqNaCJbGHN96T6k+wbZp/lnfCHFzKv0W//pyLVJdfZPyirNauDD2Ldc6B6qxneK8P6QLr+7lpGanL+7TusJNcspK/OBUlg+hEjXiBycZWDNnli1zuJrP3ue24N0RzYP8jMEI2FtvER/95SJU3d49SACFf4HdNH1NrNPn4VnJQXxooXfjgcQS0Cn488YGzISc0/luEAoGGwrI6BC/5mLT2Cx+R5Hih8LpVwpVNZMnFyW6rkb1eLnAhqXmKq4qPAFAvo+dcvIoRayugpbW3mOBCNwU51uCDiO4NjiJoTAGkIDngwZNKNsseXGxhuapT6VPKakqy55/sLL4ocW1/r/y7bnRDno0lETSLUdSHVCwUmBVS/VL5TUT/JIvxArS1UoxECtYtleXQSlVL6i4qX+f1qA5ZvxNHkYCXCcuOnE+svXsi3PucQzjLk6fw9jPgVYuEMIzTrTz8iM8sToJQ4oD8TdOT7v/V2zHIrHMD6C/kaZ665cHeB1DMghevG1dUSD7IpkTHoKy9H7z0hfEiqKqy+w/01pRpGNnoHuofo0ZnBUb9EHz7TrfELrGvmVJkYTfxtUhtGMluYCR4tr4b2/pAz1298zMiacgb+VAEfLxPNjxf5zx3sLOv0hTJw4XDDt03aABrX/P7paU/DxjATqJLZV2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
