travis:
  secure:
    BINSTAR_TOKEN: O6fowgmkWAFa0qqCkch3Qv4JTUzR9bxUtRM2cUfwodgvsZMAK+QD4snK743v8Ro+1ZgchbQwBf1LjqOh0Nh1/RY/l72xo/KuUTWgknBKoJTQ91H5gD0V4LVcifb9TfLUWwCK+N2mJNrmJwS22MPkCWtjmcosb3CMzvVbITRP0puLzTHkB4QB0aCNeZVsZvpXjlb7pnwpe09lRj6fbAyE6fTVGp9KkwX2M3a6GpHAp5BZwmGGfsfsYocyyp1jg6huTbqKKGQWU7ED+rU7YIimizan0uTkLuDnlZf/xNBw9kgT3O5NiexNpMc1bKBkaqjZL2/5zHDNCcp/y4N3TBOF1JdJDlZjUfKxB7fUXFxFWj4xvn5vsUkizqzTnUrGuge/jTFrrTVINFZVQpZzSfeuYFM2PzIdpr8o7nPPbssLC0Mzy73hqU+BuHUBEdBmWlqeu6gvtUp3WYgRnCW1q6QLCbBZiPfsoyJaxhxKS/qhaHkCvBntbna/ggQ8kGE92I54/ZxiJgdm4N79dWaGNrkr93EupV/+s/hInTVNp6ivtYPipPZhlLdz3v4NzP2alcS2vdFiECs8igLSdiTDQWjin8fUHYjYuC8Xa1O5Z0lwvzDLSiAsUBJpPJbcMCdeQ17FzQgydL8cKAQPUT/XMHcqx5NtvUAJr1Tu1+twyHc9nvg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
