appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: heEy6DuoWkxkteP5vhJG6JM6ieUWa+bSQnpVaa3w9eEQ7bZSDzm/GCLFpgzJWr6y6IEuU72ncD+wSFzwsB8tDNm4CBU09n3oDwNrk2ewp3Q66TAwRgbWRqFzgBzKErk3/SZY5vUK2hOinkThNCJiSxgZuWoyW0bAly2VIvg/4y05zz9lla1WB9PK8SuHZ1oO+OdBLbGRBRNA3FBCahcpXgjPhETySxSKUCwCUsz5J35yTKis6N6KeJ3UHxydKCtzhrfe5eDhWcetdpPTHGVxDD9No+0Q92em6NusDzWzCduQeG2c+Uwk6Es7iV14/ipUAnWwp357V/gAte+CFVLtTtJreKKjaQyivQN1dR0UT3c74DSI4hyCiY1OGljOgdu8BrZfHG0uCpEBm0Sj7UxU1eXeFtDN3HMspIxhgkuNVIJm5YrqMI4sTqJp76X6l32crnRY5BJY4Nsd3EH3jM/Ij5TffSDigSy79WW/2GbPv/HJ8vj2EHDMqq8eqmg9q0RVfkASpHKvHsWepPy2rOVVmnMzWpHnSm+JO8i3sWGS4T0dYwFaLhh5DOXuxTOk7LL05kIGki6aTr539LVFoefgC+62xUf69bVttdiRAegHPiPaVA8sEa8j2DjGWkd7S9BS8neMMcCUlRYECJEUG/ZujApm8IYGF8sHA5QmFHYTB+w=
conda_forge_output_validation: true
